title: LMSX
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://https://nirvaaww.github.io/about.html
aux_links:
  Template Repository: https://github.com/Nirvaaww/Nirvaaww.github.io
# External navigation links
nav_external_links:
  - title: More on Github
    url: https://github.com/Nirvaaww/Nirvaaww.github.io
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
