title: LMSX
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://https://nirvaaww.github.io/about.html
aux_links:
  Template Repository: https://github.com/Nirvaaww/Nirvaaww.github.io
